### ISSUE TITLE
Not able to have more than one Scala kernel running

### ISSUE THREAD

**Issue by romulogoncalves** [nlesc-sherlock/emma#48]
17/05/19 13:30:50 WARN component.AbstractLifeCycle: FAILED Spark@747f6990{HTTP/1.1}{0.0.0.0:4040}: java.net.BindException: Address already in use
May 19 13:30:50 emma0.emma.nlesc.nl jupyterhub[13694]: java.net.BindException: Address already in use
May 19 13:30:50 emma0.emma.nlesc.nl jupyterhub[13694]:         at sun.nio.ch.Net.bind0(Native Method)
May 19 13:30:50 emma0.emma.nlesc.nl jupyterhub[13694]:         at sun.nio.ch.Net.bind(Net.java:433)

**Comment by romulogoncalves** [comment]
solved.
